### ISSUE TITLE
ImportError: cannot import name 'TopologicalError'

### ISSUE THREAD

**Issue by Stablesj** [mthh/gpd_lite_toolbox#6]
Hi, 

I couldn't install the package due to an ImportError for TopologicalError from shapely.geos.

I am installing on an M1 MacBook Air, with MacOS: 13.3.1.

This is the traceback:

```python
gpd_lite_toolbox % python setup.py install
Traceback (most recent call last):
  File ".../GitHub/gpd_lite_toolbox/setup.py", line 10, in <module>
    import gpd_lite_toolbox
  File ".../GitHub/gpd_lite_toolbox/gpd_lite_toolbox/__init__.py", line 7, in <module>
    from gpd_lite_toolbox.core import (
  File ".../GitHub/gpd_lite_toolbox/gpd_lite_toolbox/core.py", line 14, in <module>
    from .utils import (
  File ".../GitHub/gpd_lite_toolbox/gpd_lite_toolbox/utils.py", line 15, in <module>
    from shapely.geos import TopologicalError
ImportError: cannot import name 'TopologicalError' from 'shapely.geos' (.../miniconda3/envs/data/lib/python3.10/site-packages/shapely/geos.py)
```

I found that replacing `geos` with `errors` in utils.py fixed this.  Source: [mail-archive.com](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1882353.html)

```python
+- from shapely.geos import TopologicalError
++ from shapely.errors import TopologicalError
```

I will create a pull request with this fix too, apologies if this is bad etiquette - this is my first time raising an issue.

**Comment by mthh** [comment]
Thank you for your feedback and your contribution !

However, I would like to point out that this repository is not actively maintained anymore and you may run into other errors (for which I would merge any PR if needed).

I'm glad you were able to find something that interests you in this package (if you need any of the features in it, feel free to copy and paste the code into your project rather than relying on this repository). 

> I will create a pull request with this fix too, apologies if this is bad etiquette - this is my first time raising an issue.

In fact, I think it's the right thing to do! Thanks!
